kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiobench-pv-claim
spec:
  storageClassName: ssd
  # storageClassName: gp2
  # storageClassName: local-storage
  # storageClassName: ibmc-block-bronze
  # storageClassName: ibmc-block-silver
  # storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fiobench
spec:
  template:
    spec:
      containers:
      - name: fiobench
        image: cbacon93/fiobench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: fiobench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: fiobench-pv
        persistentVolumeClaim:
          claimName: fiobench-pv-claim
  backoffLimit: 4
