name: Container Build And Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Autotag
        uses: phish108/autotag-action@1.1.37
        id: autotag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        
      - name: Docker setup buildx
        uses: docker/setup-buildx-action@v1.3.0
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push
        run: docker buildx build --platform linux/amd64,linux/386 -t cbacon93/fiobench:latest -t docker.pkg.github.com/${{ github.repository }}/fiobench:${{ steps.autotag.outputs.new-tag }} --push .
        
          
      
